# Dependabot configuration for AI-102 repo
# This file enables automated dependency updates for Node.js and Python projects.
# See: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2

updates:
  # Enable for all Node.js projects (npm/yarn workspaces)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"   # Options: daily, weekly, monthly
      day: "saturday"      # Run on Saturdays
      time: "09:00"        # 3am Central Time (UTC-6) = 09:00 UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - timothywarner
    labels:
      - "dependencies"
      - "dependabot"
    # Optionally, enable auto-merge for patch/minor updates
    # auto-merge: true

  # Enable for all Python projects (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - timothywarner
    labels:
      - "dependencies"
      - "dependabot"
    # auto-merge: true

# Learner Notes:
# - Dependabot will check for outdated npm and pip dependencies every Saturday at 3am Central Time (09:00 UTC).
# - It will create PRs for updates, which you can review and merge.
# - You can trigger a manual scan in the GitHub UI (Security > Dependabot).
# - For more info: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically
# - Python (pip) support added for all Python code in the repo.
